name: CI

on:
  push:
    branches:
    - master
    - feature/*

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: looking around
      run: |
        printenv
        ls -la
        pwd
        terraform --version
        cat /etc/*release
        uname -a
