name: CI

on:
  push:
    branches:
    - master
    - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: terraform apply
      env:
        SECRET: ${{ secrets.SECRET }}
      run: |
        echo "$SECRET"
        mkdir .key
        echo '{"name":"secret"}' > .key/account.json
        terraform init
        terraform validate
#        terraform plan
