name: CI

on:
  push:
    branches:
    - master
    - feature/*

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - secrets: SECRET
    - name: expose
      run: echo $SECRET
    - name: terraform apply
      run: |
        terraform --version
        terraform init
        terraform validate
        terraform plan
