name: CI

on:
  push:
    branches:
    - master
    - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: terraform apply
      env:
        TF_VAR_account_key: ${{ secrets.SECRET }}
      run: |
        terraform init
        terraform validate
        terraform plan
